// <auto-generated />
using System;
using DanmaobTisax.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DanmaobTisax.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DanmaobTisaxDbContext))]
    [Migration("20260925141945_AddPlatformAdministrators")]
    partial class AddPlatformAdministrators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DanmaobTisax.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChangedColumnsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PerformedAtUtc")
                        .HasDatabaseName("IX_AuditLog_PerformedAtUtc");

                    b.HasIndex("PerformedByUserId")
                        .HasDatabaseName("IX_AuditLog_PerformedByUserId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_AuditLog_TenantId");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("IX_AuditLog_EntityName_EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Module", "Action")
                        .HasDatabaseName("IX_Permission_Module_Action");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Identity.PlatformAdministrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLoginAttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PasswordChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_PlatformAdministrator_Email");

                    b.ToTable("PlatformAdministrators");
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshToken_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshToken_UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("IX_Role_TenantId_Name");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolePermission_RoleId_PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLoginAttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PasswordChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("IX_User_TenantId_Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserRole_UserId_RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Plans.FunctionalModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FunctionalModules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000001"),
                            Code = "Organization",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000002"),
                            Code = "Scope",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000003"),
                            Code = "Catalog",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000004"),
                            Code = "GapAnalysis",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000005"),
                            Code = "Risk",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000006"),
                            Code = "Documents",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000007"),
                            Code = "Evidence",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000008"),
                            Code = "Capa",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000009"),
                            Code = "Audits",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000010"),
                            Code = "Readiness",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000011"),
                            Code = "Dashboard",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000012"),
                            Code = "Reports",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000013"),
                            Code = "ThirdParties",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000014"),
                            Code = "Assets",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000015"),
                            Code = "PhysicalPrototype",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000016"),
                            Code = "UsersAccess",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000017"),
                            Code = "Notifications",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000018"),
                            Code = "LabelLifecycle",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000019"),
                            Code = "KnowledgeBase",
                            SortOrder = 19
                        },
                        new
                        {
                            Id = new Guid("7a0b3c20-0000-4000-8000-000000000020"),
                            Code = "Administration",
                            SortOrder = 20
                        });
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Plans.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Plan_Code");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a0b3c10-0000-4000-8000-000000000001"),
                            Code = "FREE",
                            IsActive = true,
                            Name = "Free"
                        },
                        new
                        {
                            Id = new Guid("7a0b3c10-0000-4000-8000-000000000002"),
                            Code = "BASIC",
                            IsActive = true,
                            Name = "Básico"
                        },
                        new
                        {
                            Id = new Guid("7a0b3c10-0000-4000-8000-000000000003"),
                            Code = "PREMIUM",
                            IsActive = true,
                            Name = "Premium"
                        });
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Plans.PlanModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ModuleCode");

                    b.HasIndex("PlanId", "ModuleCode")
                        .IsUnique()
                        .HasDatabaseName("IX_PlanModule_PlanId_ModuleCode");

                    b.ToTable("PlanModules");
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("7a0b3c10-0000-4000-8000-000000000001"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenant_Name");

                    b.HasIndex("PlanId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Tenants.TenantModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ModuleCode")
                        .IsUnique()
                        .HasDatabaseName("IX_TenantModule_TenantId_ModuleCode");

                    b.ToTable("TenantModules");
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("DanmaobTisax.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("DanmaobTisax.Domain.Identity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DanmaobTisax.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("DanmaobTisax.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DanmaobTisax.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Plans.PlanModule", b =>
                {
                    b.HasOne("DanmaobTisax.Domain.Plans.FunctionalModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DanmaobTisax.Domain.Plans.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DanmaobTisax.Domain.Tenants.Tenant", b =>
                {
                    b.HasOne("DanmaobTisax.Domain.Plans.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
